### ISSUE TITLE
Rerender of ad component causes crash

### ISSUE THREAD

**Issue by JoshMerlino** [SHSGames/shsgames.github.io#37]

**Comment by JoshMerlino** [comment]
```
The above error occurred in the <GoogleAdsense> component:

    at GoogleAdsense (webpack-internal:///./node_modules/react-adsense-google/dist/GoogleAdsense.js:1:1440)
    at div
    at Card (webpack-internal:///./node_modules/photoncss/lib/components/Card.js:1:2675)
    at Adsense (webpack-internal:///./web/__compile_cache/ts/components/Adsense.js:1:540)
    at div
    at Col (webpack-internal:///./node_modules/photoncss/lib/components/Layout.js:1:3321)
    at div
    at Row (webpack-internal:///./node_modules/photoncss/lib/components/Layout.js:1:2900)
    at div
    at Container (webpack-internal:///./node_modules/photoncss/lib/components/Layout.js:1:2452)
    at View
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:60:208)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:70:211)
    at main
    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:38:345)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:47:350)
    at Router (webpack-internal:///./web/__compile_cache/ts/runtime/Router.js:1:426)
    at ThemeProvider (webpack-internal:///./node_modules/photoncss/lib/components/ThemeProvider.js:1:1754)
    at Runtime (webpack-internal:///./web/__compile_cache/ts/runtime/Runtime.js:1:2067)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```
